# 자연어처리 소개

인간의 언어를 컴퓨터와 같은 기계가 묘사할 수 있도록 연구하고 구현하는 분야
1. 오늘은 컴퓨터가 자연어를 알아볼 수 있도록 하는 것을 배움/ 2. 이것을 인공지능 또는 모델링을 통해서 활용할 수 있는 것

: 음성 - Text화 -> 말뭉치 사전 기준 토큰화(오늘은 여기까지) -> 입력벡터 - 딥러닝 모델 처리(추론) -> 출력벡터 -> 말뭉치 사전 참조 Text 벡터화 -> 음성화

# 사전준비 및 라이브러리 설치

In [1]:
# 한글 형태소 분석기 mecab 설치 : 2분정도 소요
!set -x \
&& pip install konlpy \
&& curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash -x

+ pip install konlpy
     |████████████████████████████████| 19.4 MB 1.3 MB/s 
     |████████████████████████████████| 86 kB 4.4 MB/s 
     |████████████████████████████████| 448 kB 69.5 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
+ curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh
+ bash -x
+ mecab_dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic
+ set -e
++ uname
+ os=Linux
+ [[ ! Linux == \L\i\n\u\x ]]
+ hash sudo
+ sudo=sudo
+ python=python3
+ hash pyenv
+ at_user_site=
++ check_python_site_location_is_writable
++ python3 -
+ [[ 1 == \0 ]]
+ hash automake
+ echo 'Installing automake (A dependency for mecab-ko)'
Installing automake (A dependency for mecab-ko)
+ install_automake
+ '[' Linux == Linux ']'
++ grep -Ei 'debian|buntu|mint' /etc/lsb-release /etc/os-release
+ '[' '/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/l

In [2]:
# Sentencepiece 라이브러리 설치/ 사전을 만들때 필요한 라이브러리
!pip install sentencepiece

ERROR: Invalid requirement: 'sentencepiece\x1b'


# 1.음성과 Text의 상호변환

## 가.관련 라이브러리 설치 : gTTS, SpeechRecognition

In [ ]:
# text to speech(TTS 음성변환)를 위한 라이브러리
!pip install gTTS

In [ ]:
# speech to text(STT 음성인식) 처리를 위한 라이브러리
!pip3 install SpeechRecognition

     |████████████████████████████████| 32.8 MB 34 kB/s 


## 나.Text를 음성으로 변환: TTS 기술

In [ ]:
from gtts import gTTS
text ="안녕하세요, 여러분! 자연어처리 너무 재미 있지요?"

tts = gTTS(text=text, lang='ko')
tts.save("helloKO.mp3")

다운로드 받아서 들어보세요!

## 다.음성을 Text로 변환 : STT 기술

In [ ]:
!ffmpeg -i helloKO.mp3 mykor.aif 
#aif 포멧으로 바꿔줌

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lib

In [ ]:
#speech_recognition을 사용할건데 mp3파일은 안되고 aif 파일이 되기때문에 위에서 포맷을 바꿔줬어
import speech_recognition as sr

r = sr.Recognizer()
harvard = sr.AudioFile("mykor.aif") #파일 확장명이 aif를 가져와야 바로 전환돼
with harvard as source:
    audio = r.record(source)
print(r.recognize_google(audio, language='ko-KR'))

안녕하세요 여러분 자연어처리 너무 재미있지요


# 2.말뭉치 사전 만들기

말뭉치 사전 : 자연언어 연구를 위해 특정한 목적을 가지고 언어의 표본을 추출한 집합

Text를 수치화 시키는 방법은 말뭉치 사전을 만들고 그것을 기준으로 One-Hot Encoding과 BOW 방법이 있었으나 비효율 적이거나 정보의 유실이 있어 다른 방법을 모색
/지금은 말뭉치 사전을 만드는 것이 비효율적이여서 안함

## 가.말뭉치 사전 만들기

In [3]:
#모집단
corpus = """나는 학교에 다니는 학생 입니다
나는 좋은 선생님 입니다
당신은 매우 좋은 선생님 입니다"""

In [4]:
#토큰화 하는 방법은 여러가지인데 띄어쓰기 단위로 해보자
# 띄어쓰기 기준 토큰으로 분리
tokens = corpus.split()
words = list(dict.fromkeys(tokens)) #key들을 사전형으로 만들어주는 dict.fromkeys()/ 중복을 허용하지 않음
words

['나는', '학교에', '다니는', '학생', '입니다', '좋은', '선생님', '당신은', '매우']

In [ ]:
help(dict.fromkeys)

Help on built-in function fromkeys:

fromkeys(iterable, value=None, /) method of builtins.type instance
    Create a new dictionary with keys from iterable and values set to value.



In [5]:
# 각 단어에 고유한 번호 부여한 dictionary 생성
#pad는 숫자를 맞춰주기 위해서 unk(unknown) 분류가 안되는 단어 때문에 만들었어
word_to_id = {'[PAD]': 0, '[UNK]': 1}  # [PAD]: 길이 맞추는 용도, [UNK]: 알 수 없는 token
for word in words:
    word_to_id[word] = len(word_to_id)
word_to_id

{'[PAD]': 0,
 '[UNK]': 1,
 '나는': 2,
 '다니는': 4,
 '당신은': 9,
 '매우': 10,
 '선생님': 8,
 '입니다': 6,
 '좋은': 7,
 '학교에': 3,
 '학생': 5}

In [6]:
#dic형의 items를 가져올때 사용하는 거지
word_to_id.items()

dict_items([('[PAD]', 0), ('[UNK]', 1), ('나는', 2), ('학교에', 3), ('다니는', 4), ('학생', 5), ('입니다', 6), ('좋은', 7), ('선생님', 8), ('당신은', 9), ('매우', 10)])

In [7]:
# 고유한 번호로 부터 단어를 찾을 수 있는 dictionary 생성
# id와 word의 위치를 바꾸는 과정이야
id_to_word = {id:word for word, id in word_to_id.items()}
id_to_word

{0: '[PAD]',
 1: '[UNK]',
 2: '나는',
 3: '학교에',
 4: '다니는',
 5: '학생',
 6: '입니다',
 7: '좋은',
 8: '선생님',
 9: '당신은',
 10: '매우'}

In [9]:
# 말뭉치 사전 : word_to_id
corpus_dic = word_to_id
# 말뭉치 인텍스를 기준으로한 사전
corpus_id = id_to_word
# corpus depth 는 길이, 11개의 단어를 가지고 있는 말뭉치 사전이야
len(corpus_dic)

11

* 모든 단어를 포함하는 말뭉치 사전을 만들어서 각 단어에 인텍스를 부여
* 분석하고자 하는 문서를 사전의 고유한 인텍스로 수치화

## 나.One-Hot Encoding(가장 기본적인 방법)

하나의 토큰을 하나의 행벡터로 생성(단어수*사전수)

In [10]:
text = '''나는 학교에 잘 다니는 학생 입니다
선생님 은 좋은 선생님 입니다'''

In [11]:
# 줄바꿈 단위로 문장 분리
sentences = text.split("\n")
sentences

['나는 학교에 잘 다니는 학생 입니다', '선생님 은 좋은 선생님 입니다']

In [12]:
# 띄어쓰기 단위로 단어 분리/ 토큰화 하는 방법
tokens = []
for sentence in sentences:
    tokens.append(sentence.split())
tokens

[['나는', '학교에', '잘', '다니는', '학생', '입니다'], ['선생님', '은', '좋은', '선생님', '입니다']]

In [15]:
#우리가 앞서 만든 말뭉치 사전을 기준으로 분석해볼거야
# tokens을 말뭉치사전의 고유 번호로 변경(수치화 표현)
token_ids = []
for line_token in tokens:
  line_ids = []
  for token in line_token:
    if token in words:
      line_ids.append(word_to_id[token]) #말뭉치 사전에 일치하는 것이 있다면 token의 id를 넣어라
    else:
      line_ids.append(word_to_id['[UNK]']) #말뭉치 사전에 없는 말이면 unk에 넣어라 unk는 1이지
  token_ids.append(line_ids)
print(tokens,'\n',token_ids)

[['나는', '학교에', '잘', '다니는', '학생', '입니다'], ['선생님', '은', '좋은', '선생님', '입니다']] 
 [[2, 3, 1, 4, 5, 6], [8, 1, 7, 8, 6]]


In [16]:
# one hot encoding(하나의 단어를 하나의 행벡터로 표현하는 것)
# 열은 단어 사전의 수 , 행은 토큰의 수(단어의 수), 전체 행렬의 수는 문장 수
one_hot_encodings = []
for line_token in token_ids:
    print(line_token)
    one_hot_line = []  # 한 줄을 표현하는 벡터
    for id in line_token:
        # print(id)
        one_hot = [0] * len(word_to_id)  # 모두 0인 벡터를 만듬
        # print(one_hot)
        one_hot[id] = 1  # 단어 id만 1로 변경
        print(id, one_hot)
        one_hot_line.append(one_hot)  # 단어를 라인에 추가
    print(one_hot_line)
    one_hot_encodings.append(one_hot_line)  # 라인을 전체 문서에 추가

[2, 3, 1, 4, 5, 6]
2 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
3 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
1 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
4 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
5 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
6 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]
[8, 1, 7, 8, 6]
8 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
1 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
7 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
8 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
6 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]


In [17]:
# one-hot의 행렬의 구조는 문장수 * corpus_dic의 길이(열) * 토큰수(단어수,행)
one_hot_encodings

[[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]]

In [19]:
#axis의 개념을 다뤄보자
import numpy as np
# argmax는 max를 가지고 있는 index를 리턴, axis 개념 이해 필요
# shape 행렬수*행수*열수
a = np.arange(24).reshape(2,3,4) #2개의 문장 x 3행(단어의 수) x 4열(사전의 단어 수)
print(a)
print(np.argmax(a, axis=0)) # axis=0 ,reshape(2)임으로 행렬간의 비교
print(np.argmax(a, axis=1)) # axis=1, reshape(3)임으로 행간의의 비교
print(np.argmax(a, axis=2)) 
print(np.argmax(a, axis=-1)) # axis=2와 같은 결과지 열간의 비교


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]]
[[3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]]


In [ ]:
# help(np.argmax)

In [21]:
# 행기준으로 one-hot을 찾아냄/ one-hot을 가지고 수치를 만드는 것은 np.arry()
# axis = -1을 써야만 열간의 비교이기 때문에 one-hot의 정보를 가지고 행간의 argmax를 하면
# 각각이 one-hot에서 어디에 위치했는지 찾을 수 있지 즉, id의 값인거야, 1의 값을 가지고 있냐!
#one-hot을 numpy로 수치화 시켜주는 것이고
#tf를 가지고 numpy의 수치화를 다시 one-hot으로 만들어 주는 것이지
import numpy as np
print(tokens[0])
np.argmax(np.array(one_hot_encodings[0]), axis=-1)

['나는', '학교에', '잘', '다니는', '학생', '입니다']


array([2, 3, 1, 4, 5, 6])

In [22]:
# tf를 이용한 one-hot encoding, 조건: 문장들의 길이(rows)가 동일해야함 /tensorflow에서서 일괄적으로로 one-hot으로 바꿔 줄 수는 없어
import tensorflow as tf
# 열의 길이는 depth, corpus_dic 길이

tf_one_hot_encodings = tf.one_hot(indices=token_ids[0], depth=len(word_to_id))
tf_one_hot_encodings

<tf.Tensor: shape=(6, 11), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [23]:
# 문장들의 길이가 rows = 6 되도록 pad를 추가
pad_ids = []
rows=6
for line in token_ids:
    line = line[:rows]
    line += [0] * (rows - len(line))
    pad_ids.append(line)
pad_ids

[[2, 3, 1, 4, 5, 6], [8, 1, 7, 8, 6, 0]]

In [24]:
#기존 one-hot에서 마지막 행 pad가 추가된 one-hot
tf_one_hot_encodings = tf.one_hot(indices=pad_ids, depth=len(word_to_id))
tf_one_hot_encodings

<tf.Tensor: shape=(2, 6, 11), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
# [나는 학교에 잘 다니는 학생 입니다]의 one-hot encoding
import pandas as pd

df = pd.DataFrame(np.int8(tf_one_hot_encodings[1]), columns=corpus_dic.keys())
df

[PAD]  [UNK]  나는  학교에  다니는  학생  입니다  좋은  선생님  당신은  매우
0      0      0   0    0    0   0    0   0    1    0   0
1      0      1   0    0    0   0    0   0    0    0   0
2      0      0   0    0    0   0    0   1    0    0   0
3      0      0   0    0    0   0    0   0    1    0   0
4      0      0   0    0    0   0    1   0    0    0   0
5      1      0   0    0    0   0    0   0    0    0   0

## 다.BOW 생성(bag of word)

말뭉치 사전의 토큰 인덱스 위치에 토큰 출현 회수 누적, 순서 정보의 손실(빈도수로 표현)

In [27]:
sentences

['나는 학교에 잘 다니는 학생 입니다', '선생님 은 좋은 선생님 입니다']

In [28]:
# sentences의 one-hot으로부터 열 기준합계로 Bow 생성
sentence = np.sum(tf_one_hot_encodings, axis=1) #행간의 값을 전부 더하는거지
sentence

array([[0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 1., 1., 2., 0., 0.]], dtype=float32)

In [30]:
# [나는 학교에 잘 다니는 학생 입니다, 선생님 은 좋은 선생님 입니다]의 BOW 표현
# 문장에 무엇이 몇개 포함되어 있는지는 알 수 있지만 이 정보로 다시 그대로 문장을 살릴 수는 없어
#-> 벡터 인베딩 기술을 통해서 이 단점을 채울 수 있지
import pandas as pd
df = pd.DataFrame(np.int8(sentence), columns=corpus_dic.keys())
df

[PAD]  [UNK]  나는  학교에  다니는  학생  입니다  좋은  선생님  당신은  매우
0      0      1   1    1    1   1    1   0    0    0   0
1      1      1   0    0    0   0    1   1    2    0   0

# 3.다양한 형태의 토큰화

토큰화 : 일정한 입력단위로 분할

## 가.문자나 단어 단위 토큰화

In [31]:
corpus

'나는 학교에 다니는 학생 입니다\n나는 좋은 선생님 입니다\n당신은 매우 좋은 선생님 입니다'

In [ ]:
# 문자단위로 나누기: list
print(list(corpus))

['나', '는', ' ', '학', '교', '에', ' ', '다', '니', '는', ' ', '학', '생', ' ', '입', '니', '다', '\n', '나', '는', ' ', '좋', '은', ' ', '선', '생', '님', ' ', '입', '니', '다', '\n', '당', '신', '은', ' ', '매', '우', ' ', '좋', '은', ' ', '선', '생', '님', ' ', '입', '니', '다']


In [ ]:
# space 기준(띄어쓰기 단위) 단어단위 나누기 : split
print(corpus.split())

['나는', '학교에', '다니는', '학생', '입니다', '나는', '좋은', '선생님', '입니다', '당신은', '매우', '좋은', '선생님', '입니다']


## 나.형태소 기준 토큰화

In [ ]:
#띄어쓰기가 안되있더라도 복원해줌(형태소 분석기)
import konlpy
komoran = konlpy.tag.Komoran()
komoran.morphs('아버지가방에들어가신다')

['아버지', '가방', '에', '들어가', '시', 'ㄴ다']

In [ ]:
print(komoran.morphs(corpus))

['나', '는', '학교', '에', '다니', '는', '학생', '이', 'ㅂ니다', '나', '는', '좋', '은', '선생님', '이', 'ㅂ니다', '당신', '은', '매우', '좋', '은', '선생님', '이', 'ㅂ니다']


In [42]:
text = '홍길동 전화번호는 Kt 1234-5678번 입니까?'
text

'홍길동 전화번호는 Kt 1234-5678번 입니까?'

In [35]:
# 한글 형태소분석기 클래스 불러오기
from konlpy.tag import Hannanum, Komoran, Kkma, Okt

komoran = Komoran()
print(komoran.pos(text))

okt = Okt()
print(okt.pos(text))

[('[', 'SS'), ("'", 'SS'), ('홍', 'NNP'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('길', 'NNG'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('동', 'NNG'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('전', 'NNP'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('화', 'XSN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('번', 'NNB'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('호', 'NNP'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('는', 'JX'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ("K'", 'NNP'), (',', 'SP'), ("'", 'SS'), ('t', 'SL'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('1', 'SN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('2', 'SN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('3', 'SN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('4', 'SN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('-', 'SS'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('5', 'SN'), ("'", 'SS'), (',', 'SP'), ("'", 'SS'), ('6', 'SN'), ("'", 'SS'), ('

In [ ]:
# komoran.tagset

In [ ]:
# tagset 보기
print(komoran.tagset)

{'EC': '연결 어미', 'EF': '종결 어미', 'EP': '선어말어미', 'ETM': '관형형 전성 어미', 'ETN': '명사형 전성 어미', 'IC': '감탄사', 'JC': '접속 조사', 'JKB': '부사격 조사', 'JKC': '보격 조사', 'JKG': '관형격 조사', 'JKO': '목적격 조사', 'JKQ': '인용격 조사', 'JKS': '주격 조사', 'JKV': '호격 조사', 'JX': '보조사', 'MAG': '일반 부사', 'MAJ': '접속 부사', 'MM': '관형사', 'NA': '분석불능범주', 'NF': '명사추정범주', 'NNB': '의존 명사', 'NNG': '일반 명사', 'NNP': '고유 명사', 'NP': '대명사', 'NR': '수사', 'NV': '용언추정범주', 'SE': '줄임표', 'SF': '마침표, 물음표, 느낌표', 'SH': '한자', 'SL': '외국어', 'SN': '숫자', 'SO': '붙임표(물결,숨김,빠짐)', 'SP': '쉼표,가운뎃점,콜론,빗금', 'SS': '따옴표,괄호표,줄표', 'SW': '기타기호 (논리수학기호,화폐기호)', 'VA': '형용사', 'VCN': '부정 지정사', 'VCP': '긍정 지정사', 'VV': '동사', 'VX': '보조 용언', 'XPN': '체언 접두사', 'XR': '어근', 'XSA': '형용사 파생 접미사', 'XSN': '명사파생 접미사', 'XSV': '동사 파생 접미사'}


In [ ]:
# 형태소 분석
print(komoran.morphs(text)) # 형태소 분석기 마다 특징이 있
print(okt.morphs(text))

['홍길동', '전화번호', '는', 'Kt', '1234', '-', '5678', '번', '입', '니까', '?']
['홍길동', '전화번호', '는', 'Kt', '1234-5678', '번', '입', '니까', '?']


In [ ]:
# 명사추출
print(komoran.nouns(text))
print(okt.nouns(text))

['홍길동', '전화번호', '번']
['홍길동', '전화번호', '번', '입']


## 다.토큰 다루는 여러가지 방법

In [51]:
# 글자단위로 토큰화 count
import collections
char_counter = collections.Counter()
char_counter.update(list(corpus))

In [52]:
corpus

'나는 학교에 다니는 학생 입니다\n나는 좋은 선생님 입니다\n당신은 매우 좋은 선생님 입니다'

In [53]:
#빈도수를 나타내줌
print(char_counter)

Counter({' ': 11, '다': 4, '니': 4, '는': 3, '생': 3, '입': 3, '은': 3, '나': 2, '학': 2, '\n': 2, '좋': 2, '선': 2, '님': 2, '교': 1, '에': 1, '당': 1, '신': 1, '매': 1, '우': 1})


In [54]:
# 유니크한 char 개수
print(len(char_counter))

19


In [55]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [ ]:
help(collections.Counter)

In [57]:
# 빈도수가 많은 글자 10개 출력
#lambda함수를 사용하는 것??
most_freq = sorted(char_counter.items(), key=lambda item: item[1], reverse=True)
print(most_freq[:10])

[(' ', 11), ('다', 4), ('니', 4), ('는', 3), ('생', 3), ('입', 3), ('은', 3), ('나', 2), ('학', 2), ('\n', 2)]


In [ ]:
def get_key(item):
    return item[1]

most_freq = sorted(char_counter.items(), key=get_key, reverse=True)
print(most_freq[:10])

[(' ', 11), ('다', 4), ('니', 4), ('는', 3), ('생', 3), ('입', 3), ('은', 3), ('나', 2), ('학', 2), ('\n', 2)]


In [ ]:
# 빈도수가 적은 글자 10개 출력
least_freq = sorted(char_counter.items(), key=lambda item: item[1]) #reverse를 없애서 오름차순으로 만듬
print(least_freq[:10])

[('교', 1), ('에', 1), ('당', 1), ('신', 1), ('매', 1), ('우', 1), ('나', 2), ('학', 2), ('\n', 2), ('좋', 2)]


In [ ]:
# 한글 문자를 참조 인덱스로 변환 함수 ord, 참조인덱스를 한글로 변환 chr /ord()의 수는 utf-8에 고유화된 번호임
print(ord('가'),ord('힣'), chr(44032), chr(44034))
# help(ord)

44032 55203 가 갂


In [ ]:
hangul = [chr(i) for i in range(ord('가'), ord('힣') + 1)]
len(hangul)

11172

In [ ]:
print(hangul[:100])

['가', '각', '갂', '갃', '간', '갅', '갆', '갇', '갈', '갉', '갊', '갋', '갌', '갍', '갎', '갏', '감', '갑', '값', '갓', '갔', '강', '갖', '갗', '갘', '같', '갚', '갛', '개', '객', '갞', '갟', '갠', '갡', '갢', '갣', '갤', '갥', '갦', '갧', '갨', '갩', '갪', '갫', '갬', '갭', '갮', '갯', '갰', '갱', '갲', '갳', '갴', '갵', '갶', '갷', '갸', '갹', '갺', '갻', '갼', '갽', '갾', '갿', '걀', '걁', '걂', '걃', '걄', '걅', '걆', '걇', '걈', '걉', '걊', '걋', '걌', '걍', '걎', '걏', '걐', '걑', '걒', '걓', '걔', '걕', '걖', '걗', '걘', '걙', '걚', '걛', '걜', '걝', '걞', '걟', '걠', '걡', '걢', '걣']


In [ ]:
print(hangul[-100:])

['흀', '흁', '흂', '흃', '흄', '흅', '흆', '흇', '흈', '흉', '흊', '흋', '흌', '흍', '흎', '흏', '흐', '흑', '흒', '흓', '흔', '흕', '흖', '흗', '흘', '흙', '흚', '흛', '흜', '흝', '흞', '흟', '흠', '흡', '흢', '흣', '흤', '흥', '흦', '흧', '흨', '흩', '흪', '흫', '희', '흭', '흮', '흯', '흰', '흱', '흲', '흳', '흴', '흵', '흶', '흷', '흸', '흹', '흺', '흻', '흼', '흽', '흾', '흿', '힀', '힁', '힂', '힃', '힄', '힅', '힆', '힇', '히', '힉', '힊', '힋', '힌', '힍', '힎', '힏', '힐', '힑', '힒', '힓', '힔', '힕', '힖', '힗', '힘', '힙', '힚', '힛', '힜', '힝', '힞', '힟', '힠', '힡', '힢', '힣']


# 4.빅데이터 한국어 말뭉치 사전 개발

말뭉치 사전을 만드는 가장 좋은 방법은 한국어 형태소분석기와 Sentencepiece를 동시에 사용하는 것으로 알려짐 

한국어 wiki 말뭉치 : https://dumps.wikimedia.org/kowiki/ 

## 가.한국어 위키 데이터 말뭉치

In [58]:
# google drive mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [59]:
# data dir
import os
data_dir = '/content/drive/MyDrive/data'
os.listdir(data_dir)

['test1.txt',
 '4_자연어처리_소개_수정.ipynb',
 'kowiki',
 '.ipynb_checkpoints',
 'corpus',
 'corpus_5000.model',
 'corpus_5000.vocab',
 'corpus.txt',
 'test.txt',
 'example.py']

In [60]:
import os
corpus = os.path.join(data_dir, "kowiki", "kowiki.txt.zip")
corpus_dir = os.path.dirname(corpus)
corpus

'/content/drive/MyDrive/data/kowiki/kowiki.txt.zip'

In [61]:
# wiki 라인수 확인, tqdm 함수 사용시 전체 진행 경과 확인에 필요
#zipfile은 zipfile은 압축하지 않고도 사용 할 수 있게 해줘
import zipfile
from tqdm.notebook import tqdm, trange

count = 0
with zipfile.ZipFile(corpus) as z:
    with z.open('kowiki.txt') as f:
        for i, line in enumerate(tqdm(f)):
            count += 1
print(count)

0it [00:00, ?it/s]

3724301


In [62]:
# wiki 내용 확인(50줄정도만 출력)
with zipfile.ZipFile(corpus) as z:
    with z.open('kowiki.txt') as f:
        for i, line in enumerate(f):
            if i >= 50:
                break
            line = line.decode('utf-8').strip()
            print(line)

지미 카터
제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.
지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.
1962년 조지아 주 상원 의원 선거에서 낙선하나 그 선거가 부정선거 였음을 입증하게 되어 당선되고, 1966년 조지아 주 지사 선거에 낙선하지만 1970년 조지아 주 지사를 역임했다. 대통령이 되기 전 조지아주 상원의원을 두번 연임했으며, 1971년부터 1975년까지 조지아 지사로 근무했다. 조지아 주지사로 지내면서, 미국에 사는 흑인 등용법을 내세웠다.
1976년 대통령 선거에 민주당 후보로 출마하여 도덕주의 정책으로 내세워, 포드를 누르고 당선되었다.
카터 대통령은 에너지 개발을 촉구했으나 공화당의 반대로 무산되었다.
카터는 이집트와 이스라엘을 조정하여, 캠프 데이비드에서 안와르 사다트 대통령과 메나헴 베긴 수상과 함께 중동 평화를 위한 캠프데이비드 협정을 체결했다.
그러나 이것은 공화당과 미국의 유대인 단체의 반발을 일으켰다. 1979년 백악관에서 양국 간의 평화조약으로 이끌어졌다. 또한 소련과 제2차 전략 무기 제한 협상에 조인했다.
카터는 1970년대 후반 당시 대한민국 등 인권 후진국의 국민들의 인권을 지키기 위해 노력했으며, 취임 이후 계속해서 도덕정치를 내세웠다.
그러나 주 이란 미국 대사관 인질 사건에서 인질 구출 실패를 이유로 1980년 대통령 선거에서 공화당의 로널드 레이건 후보에게 져 결국 재선에 실패했다. 또한 임기 말기에 터진 소련의 아프가니스탄 침공 사건으로 인해 1980년 하계 올림픽에 반공국가들의 보이콧을 내세웠다.
지미 카터는 대한민국과의 관계에서도 중요한 영향을 미쳤던 대통

## 나.Sentencepiece 라이브러리

sentencepiece 라이브러리는 우리가 지정해주는 사전의 크기를 기준으로 단어를 문자 단위로 분해하고, 높은 빈도수 순으로 subword를 생성해서 토큰을 만들어 단어사전을 만든다.

In [68]:
!pip install sentencepiece

     |████████████████████████████████| 1.2 MB 4.2 MB/s 


In [69]:
import sentencepiece as spm
def train_sentencepiece(corpus, prefix, vocab_size=32000):
    """
    sentencepiece를 이용해 vocab 학습
    :param corpus: 학습할 말뭉치
    :param prefix: 저장할 vocab 이름
    :param vocab_size: vocab 개수
    """
    #spm안에 spmtrainer class를 사용
    spm.SentencePieceTrainer.train(
        f"--input={corpus} --model_prefix={prefix} --vocab_size={vocab_size + 7}" +  # 7은 특수문자 개수
        " --model_type=unigram" +
        " --max_sentence_length=999999" +  # 문장 최대 길이
        " --pad_id=0 --pad_piece=[PAD]" +  # pad token 및 id 지정
        " --unk_id=1 --unk_piece=[UNK]" +  # unknown token 및 id 지정
        " --bos_id=2 --bos_piece=[BOS]" +  # begin of sequence token 및 id 지정
        " --eos_id=3 --eos_piece=[EOS]" +  # end of sequence token 및 id 지정
        " --user_defined_symbols=[SEP],[CLS],[MASK]" +  # 기타 추가 토큰 SEP: 4, CLS: 5, MASK: 6
        " --input_sentence_size=100000" +  # 말뭉치에서 셈플링해서 학습
        " --shuffle_input_sentence=true")  # 셈플링한 말뭉치 shuffle

In [70]:
# 현재 작업폴더에 압축풀기
!unzip /content/drive/MyDrive/data/kowiki/kowiki.txt.zip

print(os.listdir("./"))

Archive:  /content/drive/MyDrive/data/kowiki/kowiki.txt.zip
  inflating: kowiki.txt              
  inflating: __MACOSX/._kowiki.txt   
['.config', 'drive', '__MACOSX', 'kowiki.txt', 'sample_data']


In [71]:
# 말뭉치 사전 생성
train_sentencepiece("kowiki.txt", "kowiki_32000")

In [ ]:
# 생성결과 확인
print(os.listdir("./"))

['.config', 'kowiki_32000.vocab', 'kowiki.txt', 'drive', '__MACOSX', 'mykor.aif', 'helloKO.mp3', 'kowiki_32000.model', 'sample_data']


In [ ]:
# 생성파일 백업, shutil은 파일 복제 복사 라이브러리
import shutil
corpus_dir = os.path.dirname(corpus)
shutil.copy("kowiki_32000.model", corpus_dir)
shutil.copy("kowiki_32000.vocab", corpus_dir)
shutil.copy("kowiki.txt", corpus_dir)

print(os.listdir(corpus_dir))

['kowiki.txt.zip', 'kowiki_32000.model', 'kowiki_32000.vocab', 'kowiki.txt']


In [ ]:
# 말뭉치 사전 업로드
spm_vocab = spm.SentencePieceProcessor()
spm_vocab.load(os.path.join(corpus_dir,"kowiki_32000.model"))

True

In [ ]:
# 말뭉치 사전 기준 토큰화
with zipfile.ZipFile(corpus) as z:
    with z.open('kowiki.txt') as f:
        for i, line in enumerate(f):
            if i >= 5:
                break
            line = line.decode('utf-8').strip()
            print(line)
            tokens = spm_vocab.encode_as_pieces(line)
            print(tokens)
            _ids = spm_vocab.encode_as_ids(line)
            print(_ids)

지미 카터
['▁지미', '▁카터']
[14470, 19081]
제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.
['▁제임스', '▁얼', '▁"', '지', '미', '"', '▁카터', '▁주니어', '(', ',', '▁1924', '년', '▁10', '월', '▁1', '일', '▁~', '▁)', '는', '▁민주당', '▁출신', '▁미국', '▁39', '번째', '▁대통령', '▁', '(1977', '년', '▁~', '▁1981', '년', ')', '이다', '.']
[2002, 5517, 49, 45, 167, 50, 19081, 5795, 16, 9, 5556, 17, 67, 24, 36, 30, 86, 140, 12, 2473, 702, 139, 5020, 672, 654, 10, 26492, 17, 86, 2275, 17, 13, 26, 7]
지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.
['▁지미', '▁카터', '는', '▁조지아주', '▁섬', '터', '▁카운티', '▁플레', '인', '스', '▁마을에서', '▁태어났다', '.', '▁조지아', '▁공과대학교', '를', '▁졸업', '하였다', '.', '▁그', '▁후', '▁해군', '에', '▁들어가', '▁전함', '·', '원자력', '·', '잠', '수', '함', '의', '▁승무원', '으로', '▁일', '하였다', '.', '▁1953', '년', '▁미국', '▁해군', '▁대위', '로', '▁예편', '하였고', '▁이후', '▁땅콩', '·', '면', '화', '▁등을', '▁가', '꿔', 

In [ ]:
# 문자열을 token으로 분할: encode_as_pieces
tokens = spm_vocab.encode_as_pieces("아름다운 대한민국 우리나라 금수강산")

print(tokens)

['▁아름다운', '▁대한민국', '▁우리나라', '▁금', '수', '강', '산']


In [ ]:
# token을 문자열로 복원: decode_pieces , 숫자가 다 부여 되어 있기 때문에
print(spm_vocab.decode_pieces(tokens))

아름다운 대한민국 우리나라 금수강산


In [ ]:
# 문자열을 숫자로 분할 : encode_as_ids
ids = spm_vocab.encode_as_ids("아름다운 대한민국 우리나라 금수강산")

print(ids)

[4877, 243, 6310, 653, 103, 299, 158]


In [ ]:
# 숫자를 문자열로 복원
print(spm_vocab.decode_ids(ids))

아름다운 대한민국 우리나라 금수강산


In [ ]:
# token을 숫자로 변경
print(spm_vocab.piece_to_id(tokens))

[4877, 243, 6310, 653, 103, 299, 158]


In [ ]:
# 숫자를 token으로 변경
print(spm_vocab.id_to_piece(ids))

['▁아름다운', '▁대한민국', '▁우리나라', '▁금', '수', '강', '산']


## 다.형태소분석을 이용한 말뭉치 사전 개발

In [ ]:
# 대용량 처리는 Mecab 사용 권장
from konlpy.tag import Mecab
mecab = Mecab() 
' '.join(mecab.morphs("아버지가방에들어가신다"))

'아버지 가 방 에 들어가 신다'

In [ ]:
# morph 단위로 분할된 말뭉치 생성,  mecab으로 진행시 20분 정도 소요 
from tqdm.notebook import tqdm, trange
import zipfile

with open("kowiki-mecab.txt", "w") as o_f:
    with zipfile.ZipFile(corpus) as z:
        with z.open('kowiki.txt') as f:
            for i, line in enumerate(tqdm(f, total=count)):
                line = line.decode('utf-8').strip()
                tokens = mecab.morphs(line)
                string = " ".join(tokens)
                o_f.write(string)
                o_f.write("\n")

  0%|          | 0/3724301 [00:00<?, ?it/s]

In [ ]:
# 파일 확인
print(os.listdir("./"))

['.config', 'kowiki-okt.txt', 'kowiki-mecab.txt', 'drive', 'sample_data']


In [ ]:
import shutil
corpus_dir = os.path.dirname(corpus)
shutil.copy("kowiki-mecab.txt", corpus_dir)

'/content/drive/MyDrive/Data/kowiki/kowiki-mecab.txt'

In [ ]:
# 기존 kowiki
with open(os.path.join(corpus_dir,'kowiki.txt')) as f:
    for i, line in enumerate(f):
        if i > 5:
            break
        print(line.strip())
# Mecab 형태소 분석한 kowiki /형태소단위로 나뉘어
with open(os.path.join(corpus_dir,'kowiki-mecab.txt')) as f:
    for i, line in enumerate(f):
        if i > 5:
            break
        print(line.strip())

지미 카터
제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.
지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.
1962년 조지아 주 상원 의원 선거에서 낙선하나 그 선거가 부정선거 였음을 입증하게 되어 당선되고, 1966년 조지아 주 지사 선거에 낙선하지만 1970년 조지아 주 지사를 역임했다. 대통령이 되기 전 조지아주 상원의원을 두번 연임했으며, 1971년부터 1975년까지 조지아 지사로 근무했다. 조지아 주지사로 지내면서, 미국에 사는 흑인 등용법을 내세웠다.
1976년 대통령 선거에 민주당 후보로 출마하여 도덕주의 정책으로 내세워, 포드를 누르고 당선되었다.
카터 대통령은 에너지 개발을 촉구했으나 공화당의 반대로 무산되었다.
지미 카터
제임스 얼 " 지미 " 카터 주니어 ( , 1924 년 10 월 1 일 ~ ) 는 민주당 출신 미국 39 번 째 대통령 ( 1977 년 ~ 1981 년 ) 이 다 .
지미 카터 는 조지 아주 섬터 카운티 플 레인스 마을 에서 태어났 다 . 조지 아 공과 대학교 를 졸업 하 였 다 . 그 후 해군 에 들어가 전함 · 원자력 · 잠수함 의 승무원 으로 일 하 였 다 . 1953 년 미국 해군 대위 로 예편 하 였 고 이후 땅콩 · 면화 등 을 가꿔 많 은 돈 을 벌 었 다 . 그 의 별명 이 " 땅콩 농부 " ( Peanut Farmer ) 로 알려졌 다 .
1962 년 조지아 주 상원 의원 선거 에서 낙선 하 나 그 선거 가 부정 선거 였음을 입증 하 게 되 어 당선 되 고 , 1966 년 조지아 주 지사 선거 에 낙선 하 지만 1970 년 조지아 주 지사 를 역임 했 다 . 대통

In [ ]:
# morph vocab 학습
train_sentencepiece(os.path.join(corpus_dir,'kowiki-mecab.txt'), "kowiki_mecab_32000")

In [ ]:
# 생성결과 확인
print(os.listdir("./"))

['.config', 'kowiki_mecab_32000.vocab', 'drive', 'mykor.aif', 'kowiki_mecab_32000.model', 'kowiki.txt', '__MACOSX', 'helloKO.mp3', 'kowiki_32000.model', 'kowiki_32000.vocab', 'sample_data']


In [ ]:
# 생성파일 백업
corpus_dir = os.path.dirname(corpus)
shutil.copy("kowiki_mecab_32000.model", corpus_dir)
shutil.copy("kowiki_mecab_32000.vocab", corpus_dir)

print(os.listdir(corpus_dir))

['kowiki.txt.zip', 'kowiki-mecab.txt', 'kowiki.txt', 'kowiki_32000.model', 'kowiki_32000.vocab', 'kowiki_mecab_32000.model', 'kowiki_mecab_32000.vocab']


In [ ]:
# load morph vocab
spm_morph_vocab = spm.SentencePieceProcessor()
spm_morph_vocab.load(os.path.join(corpus_dir, "kowiki_mecab_32000.model"))

True

In [ ]:
# wiki spm tokenize
with zipfile.ZipFile(corpus) as z:
    with z.open('kowiki.txt') as f:
        for i, line in enumerate(f):
            if i >= 5:
                break
            line = line.decode('utf-8').strip()
            print(line)
            tokens = spm_morph_vocab.encode_as_pieces(line)
            print(tokens)
            _ids = spm_morph_vocab.encode_as_ids(line)
            print(_ids)

지미 카터
['▁지', '미', '▁카터']
[45, 520, 8873]
제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.
['▁제임스', '▁얼', '▁"', '지', '미', '"', '▁카터', '▁주니어', '(', ',', '▁19', '24', '년', '▁10', '월', '▁1', '일', '▁~', '▁)', '는', '▁', '민주당', '▁출신', '▁미국', '▁39', '번', '째', '▁대통령', '▁(', '19', '77', '년', '▁~', '▁19', '81', '년', ')', '이', '다', '.']
[2351, 3479, 50, 75, 520, 4585, 8873, 4349, 2303, 2379, 46, 2265, 561, 110, 1917, 44, 519, 102, 18, 746, 16, 2003, 594, 125, 2837, 1914, 2135, 457, 19, 1880, 4281, 561, 102, 46, 2521, 561, 3614, 71, 220, 2543]
지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.
['▁지', '미', '▁카터', '는', '▁조지아', '주', '▁섬', '터', '▁카운티', '▁플레인', '스', '▁마을', '에', '서', '▁태어났', '다', '.', '▁조지아', '▁공과', '대', '학교', '를', '▁졸업', '하', '였', '다', '.', '▁그', '▁후', '▁해군', '에', '▁들', '어가', '▁전함', '·', '원', '자', '력', '·', '잠', '수', '함', '의', '▁승무', '원',

## 라.개발 사전 비교

In [ ]:
# 말뭉치 사전 업로드
import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.load(os.path.join(data_dir,'kowiki', "kowiki_32000.model"))
sp_morph = spm.SentencePieceProcessor()
sp_morph.load(os.path.join(data_dir,'kowiki', "kowiki_mecab_32000.model"))

True

In [ ]:
# wiki spm tokenize
import zipfile
with zipfile.ZipFile(corpus) as z:
    with z.open('kowiki.txt') as f:
        for i, line in enumerate(f):
            if i >= 5:
                break
            line = line.decode('utf-8').strip()
            print(line)
            tokens = sp.encode_as_pieces(line)
            print(tokens)
            # _ids = sp.encode_as_ids(line)
            # print(_ids)
            tokens1 = sp_morph.encode_as_pieces(line)
            print(tokens1)
            # _ids1 = sp_morph.encode_as_ids(line)
            # print(_ids1)
            print()
            

지미 카터
['▁지미', '▁카터']
['▁지', '미', '▁카터']

제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.
['▁제임스', '▁얼', '▁"', '지', '미', '"', '▁카터', '▁주니어', '(', ',', '▁1924', '년', '▁10', '월', '▁1', '일', '▁~', '▁)', '는', '▁민주당', '▁출신', '▁미국', '▁39', '번째', '▁대통령', '▁', '(1977', '년', '▁~', '▁1981', '년', ')', '이다', '.']
['▁제임스', '▁얼', '▁"', '지', '미', '"', '▁카터', '▁주니어', '(', ',', '▁19', '24', '년', '▁10', '월', '▁1', '일', '▁~', '▁)', '는', '▁', '민주당', '▁출신', '▁미국', '▁39', '번', '째', '▁대통령', '▁(', '19', '77', '년', '▁~', '▁19', '81', '년', ')', '이', '다', '.']

지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.
['▁지미', '▁카터', '는', '▁조지아주', '▁섬', '터', '▁카운티', '▁플레', '인', '스', '▁마을에서', '▁태어났다', '.', '▁조지아', '▁공과대학교', '를', '▁졸업', '하였다', '.', '▁그', '▁후', '▁해군', '에', '▁들어가', '▁전함', '·', '원자력', '·', '잠', '수', '함', '의', '▁승무원', '으로', '▁일', '하였다', '.', '▁1953', '년', '▁미국'

In [ ]:
corpus = """나는 학교에 다니는 학생 입니다
나는 좋은 선생님 입니다
당신은 매우 좋은 선생님 입니다"""

In [ ]:
print(corpus)
print(sp.encode_as_pieces(corpus))
print(sp_morph.encode_as_pieces(corpus))
print(sp_morph.encode_as_ids(corpus))

나는 학교에 다니는 학생 입니다
나는 좋은 선생님 입니다
당신은 매우 좋은 선생님 입니다
['▁나는', '▁학교에', '▁다니는', '▁학생', '▁', '입니다', '▁나는', '▁좋은', '▁선생님', '▁', '입니다', '▁당신', '은', '▁매우', '▁좋은', '▁선생님', '▁', '입니다']
['▁나', '는', '▁학교', '에', '▁다니', '는', '▁학생', '▁입니다', '▁나', '는', '▁좋', '은', '▁선생', '님', '▁입니다', '▁당', '신', '은', '▁매우', '▁좋', '은', '▁선생', '님', '▁입니다']
[79, 746, 200, 711, 2821, 746, 911, 3675, 79, 746, 602, 509, 2325, 1320, 3675, 244, 402, 509, 585, 602, 509, 2325, 1320, 3675]


In [ ]:
# vocab 사이즈를 출력합니다.
print(sp_morph.get_piece_size())

32007


In [ ]:
# 모두 출력 
for id in range(20):
  print(sp_morph.id_to_piece(id), sp.is_control(id))

[PAD] True
[UNK] False
[BOS] True
[EOS] True
[SEP] False
[CLS] False
[MASK] False
▁. False
▁의 False
▁다 False
▁이 False
▁는 False
▁, False
▁에 False
▁을 False
▁하 False
▁ False
▁은 False
▁) False
▁( False


In [ ]:
# 아이디는 piece로 piece는 아이디로 반환합니다.
print(sp_morph.id_to_piece(9))
print(sp_morph.piece_to_id('▁나'))

# 알수 없는 토큰의 겨우 1을 반환합니다.
print(sp_morph.piece_to_id('__MUST_BE_UNKNOWN__'))

▁다
79
1


In [ ]:
# morph 개수
tokens1 = sp.encode_as_pieces(corpus)
tokens2 = sp_morph.encode_as_pieces(corpus)
print(len(tokens1),len(tokens2))

18 24
